// Phase 4 Plan 03 Task 1 — migration emitter.
//
// Pure functions producing { file_path, file_content } for the two
// deterministic promotion kinds (Filter rule + Known sender). Operator-
// controlled string fields are PostgreSQL-dollar-quoted ($promo_payload$...$)
// so a malicious subject_pattern or sender_pattern containing single quotes
// or SQL syntax can never break out of the string literal (threat T-04-03-09).
//
// Identifier-shaped fields (candidate_id, swarm_type, timestamp_utc,
// customer_account_id, operator_id) are validated against strict allowlist
// regex — anything outside the regex throws synchronously. The server action
// that calls these emitters catches + returns a structured ActionResult.
//
// IMPORTANT: This module NEVER writes to the filesystem. The Apply server
// action returns { migration_path, migration_content } to the operator UI;
// an engineer pastes the content into the new file as part of normal repo
// PR flow (P4-D-08 — engineer-led-application invariant).

export const MIGRATION_DIR = "supabase/migrations";

const DOLLAR_TAG = "promo_payload";
const UUID_RE = /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const SWARM_RE = /^[a-z][a-z0-9_-]*$/i;
const TS_RE = /^\d{12}$/;
const NUMERIC_RE = /^[0-9]+$/;

function shortId(candidate_id: string): string {
  return candidate_id.replace(/-/g, "").slice(0, 8).toLowerCase();
}

function dq(value: string): string {
  return `$${DOLLAR_TAG}$${value}$${DOLLAR_TAG}$`;
}

function validateCommon(args: { candidate_id: string; swarm_type: string; timestamp_utc: string }) {
  if (!UUID_RE.test(args.candidate_id)) throw new Error("invalid candidate_id");
  if (!SWARM_RE.test(args.swarm_type)) throw new Error("invalid swarm_type");
  if (!TS_RE.test(args.timestamp_utc)) throw new Error("invalid timestamp");
}

export interface EmitFilterRuleArgs {
  candidate_id: string;
  swarm_type: string;
  subject_pattern: string;
  sender_filter?: string[] | null;
  timestamp_utc: string;
}

export function emitFilterRuleMigration(args: EmitFilterRuleArgs): {
  file_path: string;
  file_content: string;
} {
  validateCommon(args);
  const short = shortId(args.candidate_id);
  const file_path = `${MIGRATION_DIR}/${args.timestamp_utc}_promotion_${short}_filter_rule.sql`;

  const senderArray =
    args.sender_filter && args.sender_filter.length > 0
      ? `ARRAY[${args.sender_filter.map((s) => dq(s)).join(", ")}]`
      : "NULL";

  // INSERT INTO public.classifier_rules — column shape per
  // supabase/migrations/20260428_classifier_rules.sql:
  //   id (default), swarm_type, rule_key, kind, status, n, agree, ... notes ...
  // Approved candidates land as status='candidate' so the engineer reviewing
  // the migration can promote → 'promoted' explicitly via the existing
  // classifier-rules promotion path. Promotion-recommender lineage is stored
  // in `notes` (operator-readable text — no schema change required).
  const file_content = `BEGIN;

-- Auto-generated by promotion-recommender Apply
-- candidate_id: ${args.candidate_id}
-- swarm:        ${args.swarm_type}
-- kind:         Filter rule (regex_rule)
-- Engineer: review the subject_pattern + sender_filter below, then commit.
-- Rollback: DELETE FROM public.classifier_rules WHERE rule_key = 'promo_${short}';

INSERT INTO public.classifier_rules (rule_key, swarm_type, kind, status, notes)
VALUES (
  ${dq(`promo_${short}`)},
  ${dq(args.swarm_type)},
  'regex',
  'candidate',
  ${dq(`subject_pattern=${args.subject_pattern} | sender_filter=${args.sender_filter ? args.sender_filter.join(",") : "ANY"} | source=promotion_recommender | candidate_id=${args.candidate_id}`)}
)
ON CONFLICT (swarm_type, rule_key) DO UPDATE
  SET notes = EXCLUDED.notes,
      updated_at = now();

-- Pattern body (for engineer reference; classifier_rules schema does not
-- carry subject_pattern/sender_filter columns directly — they live in the
-- code-side rule registry. The notes column above carries the operator-
-- approved values so engineering can wire them into the registry).
-- subject_pattern: ${dq(args.subject_pattern)}
-- sender_filter:   ${senderArray}

COMMIT;
`;
  return { file_path, file_content };
}

export interface EmitKnownSenderArgs {
  candidate_id: string;
  swarm_type: string;
  sender_pattern: string;
  customer_account_id: string;
  operator_id: string;
  timestamp_utc: string;
}

export function emitKnownSenderMigration(args: EmitKnownSenderArgs): {
  file_path: string;
  file_content: string;
} {
  validateCommon(args);
  if (!NUMERIC_RE.test(args.customer_account_id))
    throw new Error("invalid customer_account_id");
  if (!UUID_RE.test(args.operator_id)) throw new Error("invalid operator_id");
  const short = shortId(args.candidate_id);
  const file_path = `${MIGRATION_DIR}/${args.timestamp_utc}_promotion_${short}_known_sender.sql`;

  const file_content = `BEGIN;

-- Auto-generated by promotion-recommender Apply
-- candidate_id: ${args.candidate_id}
-- swarm:        ${args.swarm_type}
-- kind:         Known sender (sender_mapping)
-- Engineer: review the sender→customer mapping below, then commit.
-- Rollback: DELETE FROM debtor.sender_customer_map WHERE sender_email = ${dq(args.sender_pattern)};

INSERT INTO debtor.sender_customer_map (
  sender_email,
  customer_account_id,
  swarm_type,
  source,
  promotion_candidate_id,
  created_by
)
VALUES (
  ${dq(args.sender_pattern)},
  ${dq(args.customer_account_id)},
  ${dq(args.swarm_type)},
  'promotion_recommender',
  '${args.candidate_id}'::uuid,
  '${args.operator_id}'::uuid
)
ON CONFLICT (sender_email) DO UPDATE
  SET customer_account_id = EXCLUDED.customer_account_id,
      swarm_type = EXCLUDED.swarm_type,
      source = 'promotion_recommender',
      promotion_candidate_id = EXCLUDED.promotion_candidate_id,
      created_by = EXCLUDED.created_by;

COMMIT;
`;
  return { file_path, file_content };
}
