// Phase 69 (CANO-02, D-03). Codegen script: reads swarms.entity_brand from the
// live registry and writes a generated TS literal-union to
// web/lib/automations/debtor-email/coordinator/entity.generated.ts.
//
// Why: keeps strict TS compile-time safety AND zero-edit onboarding. After a
// new brand row is INSERTed into the registry, run `npm run codegen` and
// commit the regenerated file. Operator never edits the .generated.ts by hand.
//
// Run:   npx tsx scripts/gen-entity-types.ts
// CI:    npm run codegen
//
// Idempotent: if the on-disk content already matches, prints "already
// up-to-date" and exits 0 without rewriting (preserves mtime; clean diff).

import { createClient } from "@supabase/supabase-js";
import {
  writeFileSync,
  mkdirSync,
  readFileSync,
  existsSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { config as loadDotenv } from "dotenv";
import { loadAllBrandRegisters } from "../lib/swarms/brand-register";

loadDotenv({ path: resolve(__dirname, "..", ".env.local") });

const OUTPUT_PATH = resolve(
  __dirname,
  "..",
  "lib",
  "automations",
  "debtor-email",
  "coordinator",
  "entity.generated.ts",
);

const HEADER = `// AUTO-GENERATED by scripts/gen-entity-types.ts (Phase 69 / CANO-02 / D-03).
// DO NOT EDIT BY HAND. Run \`npm run codegen\` after registry changes.
//
// Source of truth: public.swarms.entity_brand (jsonb, Phase 69 shape).
// Regenerate when a new brand is INSERTed into the registry.

`;

function renderBody(codes: string[]): string {
  if (codes.length === 0) {
    // Defensive: an empty registry shouldn't happen in practice, but emit a
    // valid TS file anyway so the build doesn't break in dev.
    return `export const ENTITY_BRANDS = [] as const;\nexport type Entity = never;\n`;
  }
  const sorted = [...codes].sort();
  const tupleEntries = sorted.map((c) => `  "${c}",`).join("\n");
  return (
    `export const ENTITY_BRANDS = [\n${tupleEntries}\n] as const;\n\n` +
    `export type Entity = (typeof ENTITY_BRANDS)[number];\n`
  );
}

async function main(): Promise<void> {
  const url =
    process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_SERVICE_KEY;
  if (!url || !key) {
    throw new Error(
      "[gen-entity-types] SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) + SUPABASE_SERVICE_ROLE_KEY required",
    );
  }
  const admin = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const swarmType = process.env.SWARM_TYPE ?? "debtor-email";
  const brands = await loadAllBrandRegisters(admin, swarmType);
  const codes = brands.map((b) => b.code);

  const next = HEADER + renderBody(codes);

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  const existing = existsSync(OUTPUT_PATH)
    ? readFileSync(OUTPUT_PATH, "utf8")
    : null;

  if (existing === next) {
    console.log(
      `[gen-entity-types] already up-to-date (${codes.length} brand codes) — no write`,
    );
    return;
  }

  writeFileSync(OUTPUT_PATH, next, "utf8");
  console.log(
    `[gen-entity-types] wrote ${codes.length} brand codes (${codes
      .slice()
      .sort()
      .join(", ")}) to ${OUTPUT_PATH}`,
  );
}

main().catch((err) => {
  console.error("[gen-entity-types] FAILED:", err);
  process.exit(1);
});
