// Phase 69 (CANO-02, D-03). Codegen script: reads swarms.entity_brand from the
// live registry and writes a generated TS literal-union to
// web/lib/automations/debtor-email/coordinator/entity.generated.ts.
//
// Why: keeps strict TS compile-time safety AND zero-edit onboarding. After a
// new brand row is INSERTed into the registry, run `npm run codegen` and
// commit the regenerated file. Operator never edits the .generated.ts by hand.
//
// Wave 0 (this commit) ships the script skeleton only. The script runs but
// will throw `MalformedRegistryError` against a live DB until Wave 1 applies
// the entity_brand expansion migration. CI hookup (npm run codegen) lights up
// in Wave 2.
//
// Run:   npx tsx scripts/gen-entity-types.ts
// CI:    npm run codegen (added in Wave 2 alongside the package.json script entry)

import { createClient } from "@supabase/supabase-js";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { loadAllBrandRegisters } from "../lib/swarms/brand-register";

const OUTPUT_PATH = resolve(
  __dirname,
  "..",
  "lib",
  "automations",
  "debtor-email",
  "coordinator",
  "entity.generated.ts",
);

const HEADER = `// AUTO-GENERATED by web/scripts/gen-entity-types.ts (Phase 69 / CANO-02 / D-03).
// DO NOT EDIT BY HAND. Run \`npm run codegen\` after registry changes.
//
// Source of truth: public.swarms.entity_brand (jsonb, Phase 69 shape).
// Regenerate when a new brand is INSERTed into the registry.

`;

function renderUnion(codes: string[]): string {
  if (codes.length === 0) {
    // Defensive: an empty registry shouldn't happen in practice, but emit a
    // valid TS file anyway so the build doesn't break in dev.
    return "export type Entity = never;\n";
  }
  const sortedQuoted = [...codes].sort().map((c) => `  | "${c}"`);
  return `export type Entity =\n${sortedQuoted.join("\n")};\n\nexport const ENTITY_CODES: readonly Entity[] = [\n${[...codes]
    .sort()
    .map((c) => `  "${c}",`)
    .join("\n")}\n] as const;\n`;
}

async function main(): Promise<void> {
  const url = process.env.SUPABASE_URL;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_SERVICE_KEY;
  if (!url || !key) {
    throw new Error(
      "[gen-entity-types] SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY required",
    );
  }
  const admin = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const swarmType = process.env.SWARM_TYPE ?? "debtor-email";
  const brands = await loadAllBrandRegisters(admin, swarmType);
  const codes = brands.map((b) => b.code);

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, HEADER + renderUnion(codes), "utf8");
  console.log(
    `[gen-entity-types] wrote ${codes.length} brand codes to ${OUTPUT_PATH}`,
  );
}

main().catch((err) => {
  console.error("[gen-entity-types] FAILED:", err);
  process.exit(1);
});
