// Phase 84 (D-03). Codegen script: reads swarms.tenant_domains from the
// live registry and writes a generated TS per-swarm map + literal-union to
// web/lib/automations/debtor-email/coordinator/tenant-domains.generated.ts.
//
// Why: registry is source-of-truth for tenant domains (own_outbound_invoice_loopback
// rule + coordinator assembleInput dependency); strict TS compile-time
// safety is preserved via a literal-union TenantDomain type. Operator never
// edits the .generated.ts by hand.
//
// Run:   npx tsx scripts/gen-tenant-domains.ts
// CI:    npm run codegen (chains with gen-entity-types.ts)
//
// Idempotent: if the on-disk content already matches, prints "already
// up-to-date" and exits 0 without rewriting (preserves mtime; clean diff).
//
// Output shape (per-swarm map, per RESEARCH Open Q #4 — debtor-email and
// sales-email have disjoint tenant-domain sets):
//   export const TENANT_DOMAINS_BY_SWARM = {
//     "debtor-email": ["fire-control.nl","moyneroberts.com","smeba-fire.be","smeba.nl"],
//     "sales-email":  ["smeba.nl"],
//   } as const;
//   export type TenantDomain = (typeof TENANT_DOMAINS_BY_SWARM)[keyof typeof TENANT_DOMAINS_BY_SWARM][number];

import { createClient } from "@supabase/supabase-js";
import {
  writeFileSync,
  mkdirSync,
  readFileSync,
  existsSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { config as loadDotenv } from "dotenv";

loadDotenv({ path: resolve(__dirname, "..", ".env.local") });

const OUTPUT_PATH = resolve(
  __dirname,
  "..",
  "lib",
  "automations",
  "debtor-email",
  "coordinator",
  "tenant-domains.generated.ts",
);

const HEADER = `// AUTO-GENERATED by scripts/gen-tenant-domains.ts (Phase 84 / D-03).
// DO NOT EDIT BY HAND. Run \`npm run codegen\` after registry changes.
//
// Source of truth: public.swarms.tenant_domains (jsonb array of lowercase
// domain strings). Regenerate when a swarm's tenant_domains list changes.

`;

interface SwarmTenantRow {
  swarm_type: string;
  tenant_domains: string[] | null;
}

function renderBody(rows: SwarmTenantRow[]): string {
  if (rows.length === 0) {
    // Defensive: shouldn't happen in practice, but emit a valid file so the
    // build doesn't break in dev.
    return (
      `export const TENANT_DOMAINS_BY_SWARM = {} as const;\n\n` +
      `export type TenantDomain = never;\n`
    );
  }
  // Stable diff: sort rows by swarm_type and sort each domain list
  // alphabetically. The DB query already ORDER BY swarm_type but resort
  // defensively in case the query is changed later.
  const sortedRows = [...rows].sort((a, b) =>
    a.swarm_type.localeCompare(b.swarm_type),
  );
  const entries = sortedRows
    .map((r) => {
      const domains = [...(r.tenant_domains ?? [])]
        .map((d) => d.toLowerCase())
        .sort();
      const list = domains.map((d) => `"${d}"`).join(", ");
      return `  ${JSON.stringify(r.swarm_type)}: [${list}],`;
    })
    .join("\n");
  return (
    `export const TENANT_DOMAINS_BY_SWARM = {\n${entries}\n} as const;\n\n` +
    `export type TenantDomain =\n  (typeof TENANT_DOMAINS_BY_SWARM)[keyof typeof TENANT_DOMAINS_BY_SWARM][number];\n`
  );
}

async function main(): Promise<void> {
  const url =
    process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_SERVICE_KEY;
  if (!url || !key) {
    throw new Error(
      "[gen-tenant-domains] SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) + SUPABASE_SERVICE_ROLE_KEY required",
    );
  }
  const admin = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const { data, error } = await admin
    .from("swarms")
    .select("swarm_type, tenant_domains")
    .order("swarm_type");
  if (error) {
    throw new Error(
      `[gen-tenant-domains] query failed: ${error.message}. If the column does not exist yet, push Phase 84 migration 20260520_phase84_tenant_domains.sql first.`,
    );
  }

  const rows: SwarmTenantRow[] = (data ?? []).map((r) => ({
    swarm_type: r.swarm_type as string,
    tenant_domains: Array.isArray(r.tenant_domains)
      ? (r.tenant_domains as string[])
      : null,
  }));

  const next = HEADER + renderBody(rows);

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  const existing = existsSync(OUTPUT_PATH)
    ? readFileSync(OUTPUT_PATH, "utf8")
    : null;

  if (existing === next) {
    console.log(
      `[gen-tenant-domains] already up-to-date (${rows.length} swarm rows) — no write`,
    );
    return;
  }

  writeFileSync(OUTPUT_PATH, next, "utf8");
  console.log(
    `[gen-tenant-domains] wrote ${rows.length} swarm rows to ${OUTPUT_PATH}`,
  );
}

main().catch((err) => {
  console.error("[gen-tenant-domains] FAILED:", err);
  process.exit(1);
});
