// Phase 1 (milestone bulk-review-flow-ux / CON-swarm-intents-codegen). Codegen
// script: reads swarm_intents.intent_key from the live registry and writes a
// generated TS literal-union to
// web/lib/automations/debtor-email/coordinator/intent.generated.ts.
//
// Why: keeps strict TS compile-time safety AND zero-edit onboarding. After a
// new intent row is INSERTed into swarm_intents, run `npm run codegen` and
// commit the regenerated file. Operator never edits the .generated.ts by hand.
//
// Mirrors web/scripts/gen-entity-types.ts (Phase 69 / D-03).
//
// Run:   npx tsx scripts/gen-intent-types.ts
// CI:    npm run codegen
//
// Idempotent: if the on-disk content already matches, prints "already
// up-to-date" and exits 0 without rewriting (preserves mtime; clean diff).

import { createClient } from "@supabase/supabase-js";
import {
  writeFileSync,
  mkdirSync,
  readFileSync,
  existsSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { config as loadDotenv } from "dotenv";

loadDotenv({ path: resolve(__dirname, "..", ".env.local") });

const OUTPUT_PATH = resolve(
  __dirname,
  "..",
  "lib",
  "automations",
  "debtor-email",
  "coordinator",
  "intent.generated.ts",
);

const HEADER = `// AUTO-GENERATED by scripts/gen-intent-types.ts (Phase 1 milestone bulk-review-flow-ux / CON-swarm-intents-codegen).
// DO NOT EDIT BY HAND. Run \`npm run codegen\` after registry changes.
//
// Source of truth: public.swarm_intents.intent_key (Phase 68 registry).
// Regenerate when a new intent is INSERTed into the registry.

`;

function renderBody(keys: string[]): string {
  if (keys.length === 0) {
    // Defensive: an empty registry shouldn't happen in practice, but emit a
    // valid TS file anyway so the build doesn't break in dev.
    return `export const SWARM_INTENTS = [] as const;\nexport type Intent = never;\n`;
  }
  const sorted = [...keys].sort();
  const tupleEntries = sorted.map((k) => `  "${k}",`).join("\n");
  return (
    `export const SWARM_INTENTS = [\n${tupleEntries}\n] as const;\n\n` +
    `export type Intent = (typeof SWARM_INTENTS)[number];\n`
  );
}

export async function main(): Promise<void> {
  const url =
    process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_SERVICE_KEY;
  if (!url || !key) {
    throw new Error(
      "[gen-intent-types] SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) + SUPABASE_SERVICE_ROLE_KEY required",
    );
  }
  const admin = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const swarmType = process.env.SWARM_TYPE ?? "debtor-email";
  // NOTE: public.swarm_intents has no `enabled` column (see migration
  // 20260504b_swarms_registry_generalisation.sql) — all rows are implicitly
  // enabled. Plan 01-01 instruction included an .eq("enabled", true) filter
  // that does not match the live schema; Rule 1 deviation: filter dropped.
  const { data, error } = await admin
    .from("swarm_intents")
    .select("intent_key")
    .eq("swarm_type", swarmType);
  if (error) {
    throw new Error(
      `[gen-intent-types] swarm_intents query failed: ${error.message}`,
    );
  }
  const keys: string[] = (data ?? []).map(
    (r: { intent_key: string }) => r.intent_key,
  );

  const next = HEADER + renderBody(keys);

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  const existing = existsSync(OUTPUT_PATH)
    ? readFileSync(OUTPUT_PATH, "utf8")
    : null;

  if (existing === next) {
    console.log(
      `[gen-intent-types] already up-to-date (${keys.length} intent keys) — no write`,
    );
    return;
  }

  writeFileSync(OUTPUT_PATH, next, "utf8");
  console.log(
    `[gen-intent-types] wrote ${keys.length} intent keys (${[...keys]
      .sort()
      .join(", ")}) to ${OUTPUT_PATH}`,
  );
}

// Auto-run when executed via `tsx scripts/gen-intent-types.ts` (mirrors
// gen-entity-types.ts). The `require.main === module` guard prevents
// accidental execution if this file is ever imported (Test 1 contract).
if (require.main === module) {
  main().catch((err) => {
    console.error("[gen-intent-types] FAILED:", err);
    process.exit(1);
  });
}
