// AUTO-GENERATED by scripts/gen-entity-types.ts (Phase 69 / CANO-02 / D-03).
// DO NOT EDIT BY HAND. Run `npm run codegen` after registry changes.
//
// Source of truth: public.swarms.entity_brand (jsonb, Phase 69 shape).
// Regenerate when a new brand is INSERTed into the registry.

export const ENTITY_BRANDS = [
  "berki",
  "sicli-noord",
  "sicli-sud",
  "smeba",
  "smeba-fire",
] as const;

export type Entity = (typeof ENTITY_BRANDS)[number];
