// AUTO-GENERATED by scripts/gen-intent-types.ts (Phase 1 milestone bulk-review-flow-ux / CON-swarm-intents-codegen).
// DO NOT EDIT BY HAND. Run `npm run codegen` after registry changes.
//
// Source of truth: public.swarm_intents.intent_key (Phase 68 registry).
// Regenerate when a new intent is INSERTed into the registry.

export const SWARM_INTENTS = [
  "address_change",
  "contract_inquiry",
  "copy_document_request",
  "credit_request",
  "general_inquiry",
  "invoice_copy_request",
  "other",
  "payment_dispute",
  "peppol_request",
] as const;

export type Intent = (typeof SWARM_INTENTS)[number];
