// AUTO-GENERATED by scripts/gen-tenant-domains.ts (Phase 84 / D-03).
// DO NOT EDIT BY HAND. Run `npm run codegen` after registry changes.
//
// Source of truth: public.swarms.tenant_domains (jsonb array of lowercase
// domain strings). Regenerate when a swarm's tenant_domains list changes.

export const TENANT_DOMAINS_BY_SWARM = {
  "debtor-email": ["fire-control.nl", "moyneroberts.com", "smeba-fire.be", "smeba.nl"],
  "info-routing": ["berki.nl", "fire-control.nl", "moyneroberts.com", "sicli-noord.be", "sicli-sud.be", "smeba-fire.be", "smeba.nl"],
  "sales-email": ["smeba.nl"],
  "support-tickets": [],
} as const;

export type TenantDomain =
  (typeof TENANT_DOMAINS_BY_SWARM)[keyof typeof TENANT_DOMAINS_BY_SWARM][number];
